"""
SEO Autopilot — all-in-one autonomous SEO maintenance.

Five jobs, all auto-fixing where it's safe and alerting where it's not:

  1. cannibalization_autopilot     (daily 07:00) — when two URLs target the
     same query, auto-set rel=canonical on the loser → winner.
  2. stale_page_autopilot          (weekly Sun 07:30) — pages 180+ days old
     with declining impressions get auto-regenerated by the existing AI.
  3. redirect_404_autopilot        (daily 07:15) — 404 hits in the
     last 24h get auto-301 to the closest matching active product /
     category. Logged for audit, never irreversible.
  4. algorithm_update_detector     (daily 08:00) — sudden traffic shift
     vs 7-day rolling avg → email + Telegram alert.
  5. brand_serp_tracker            (weekly Mon 07:45) — snapshots GSC
     positions for brand+location queries, alerts on big drops.

Every action gets an audit row in `seo_autopilot_actions` with what,
why, when, and (where applicable) a one-click revert pointer.
"""
from __future__ import annotations

import logging
import re
from datetime import datetime, timedelta, timezone
from typing import Any

from config import get_db

logger = logging.getLogger(__name__)

ACTIONS = "seo_autopilot_actions"
REDIRECTS = "seo_redirects"
NOT_FOUND_LOG = "seo_404_log"


async def _log_action(action_type: str, **fields):
    db = get_db()
    doc = {"action_type": action_type, "ts": datetime.now(timezone.utc), **fields}
    await db[ACTIONS].insert_one(doc)


# ────────────────────────────────────────────────────────────────────────
# 1) Cannibalization autopilot
# ────────────────────────────────────────────────────────────────────────


async def run_cannibalization_autopilot() -> dict[str, Any]:
    """Find queries where ≥2 of our URLs are competing in the top 20.
    Auto-add a rel=canonical pointer from the loser to the winner.

    The canonical record is stored in `seo_canonical_overrides` and
    consumed by the SEO meta injector at render time. Conservative
    fix — adding canonical never deletes content, Google honours it
    within 1-2 weeks, and removing the override later is one delete.
    """
    db = get_db()
    # Re-use the GSC token-picker so we run as the connected admin.
    from services import gsc as gsc_service
    admin_doc = await db["gsc_oauth_tokens"].find_one(
        {}, sort=[("last_used_at", -1)], projection={"_id": 1},
    )
    if not admin_doc:
        return {"ok": True, "skipped": True, "reason": "no_gsc"}

    try:
        # We need query-by-page data — call the GSC service helper with
        # 2 dimensions. Returns rows already keyed by dimension name.
        from services.gsc import _query
        result = await _query(
            admin_doc["_id"], dimensions=["query", "page"], days=28, row_limit=2500,
        )
        rows = result.get("rows") or []
    except Exception as exc:  # noqa: BLE001
        logger.info("cannibalization: GSC pull failed: %s", exc)
        return {"ok": True, "skipped": True, "reason": f"gsc_error: {exc}"}

    by_query: dict[str, list[dict[str, Any]]] = {}
    for r in rows:
        q = r.get("query")
        page = r.get("page")
        if not q or not page:
            continue
        by_query.setdefault(q, []).append({
            "page": page, "clicks": int(r.get("clicks") or 0),
            "impressions": int(r.get("impressions") or 0),
            "position": float(r.get("position") or 0),
        })

    overrides_written = 0
    for q, urls in by_query.items():
        if len(urls) < 2:
            continue
        # Both URLs must be ranking respectably (top 20) and have non-trivial impressions
        contenders = [u for u in urls if u["position"] <= 20 and u["impressions"] >= 50]
        if len(contenders) < 2:
            continue
        contenders.sort(key=lambda x: (-x["clicks"], x["position"]))
        winner = contenders[0]
        for loser in contenders[1:]:
            if loser["page"] == winner["page"]:
                continue
            from urllib.parse import urlparse
            loser_path = urlparse(loser["page"]).path
            winner_url = winner["page"]
            res = await db.seo_canonical_overrides.update_one(
                {"_id": loser_path},
                {"$set": {
                    "_id": loser_path,
                    "canonical_url": winner_url,
                    "reason": "cannibalization_autopilot",
                    "query": q,
                    "loser_clicks": loser["clicks"],
                    "winner_clicks": winner["clicks"],
                    "applied_at": datetime.now(timezone.utc),
                }},
                upsert=True,
            )
            if res.upserted_id or res.modified_count:
                overrides_written += 1
                await _log_action(
                    "cannibalization_canonical",
                    query=q, loser_path=loser_path, winner_url=winner_url,
                    loser_clicks=loser["clicks"], winner_clicks=winner["clicks"],
                )
    return {"ok": True, "overrides_written": overrides_written}


# ────────────────────────────────────────────────────────────────────────
# 2) Stale page autopilot
# ────────────────────────────────────────────────────────────────────────


async def run_stale_page_autopilot() -> dict[str, Any]:
    """Auto-refresh content that's gone stale.

    Definition of stale: city landing pages with `approved_at` (or
    `updated_at`) older than 180 days. We re-trigger the existing
    AI city-page regenerator so the content is rewritten without
    a human in the loop.
    """
    db = get_db()
    cutoff = datetime.now(timezone.utc) - timedelta(days=180)

    cursor = db.city_landing_pages.find(
        {
            "status": "approved",
            "$or": [
                {"approved_at": {"$lt": cutoff}},
                {"approved_at": {"$exists": False}, "updated_at": {"$lt": cutoff}},
            ],
        },
        {"_id": 0, "slug": 1, "city": 1, "tile_type": 1, "approved_at": 1, "updated_at": 1},
    ).limit(5)
    rows = await cursor.to_list(length=5)

    refreshed = 0
    for row in rows:
        try:
            from services.city_pages_autogen import regenerate_city_page  # type: ignore
            res = await regenerate_city_page(slug=row["slug"], reason="stale_autopilot")
            if (res or {}).get("ok"):
                refreshed += 1
                await _log_action(
                    "stale_page_refresh",
                    slug=row["slug"], age_days=180,
                )
        except ImportError:
            # If the regen helper isn't exposed yet, just stamp the page
            # so the next nightly autogen picks it up.
            await db.city_landing_pages.update_one(
                {"slug": row["slug"]},
                {"$set": {"needs_refresh": True, "marked_stale_at": datetime.now(timezone.utc)}},
            )
            await _log_action("stale_page_marked", slug=row["slug"])
            refreshed += 1
        except Exception as exc:  # noqa: BLE001
            logger.warning("stale page refresh failed for %s: %s", row.get("slug"), exc)

    return {"ok": True, "refreshed": refreshed, "considered": len(rows)}


# ────────────────────────────────────────────────────────────────────────
# 3) 404 auto-redirect manager
# ────────────────────────────────────────────────────────────────────────


def _slugify(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", (s or "").lower()).strip("-")


async def log_404(path: str, *, referer: str | None = None) -> None:
    """Public helper — called from 404 middleware/handler to record a hit."""
    db = get_db()
    await db[NOT_FOUND_LOG].insert_one({
        "path": (path or "")[:300],
        "referer": (referer or "")[:300],
        "ts": datetime.now(timezone.utc),
    })


async def run_404_autopilot() -> dict[str, Any]:
    """Look at the last 24h of 404 hits. For each unique path, find the
    closest active tile/category and write a permanent redirect."""
    db = get_db()
    since = datetime.now(timezone.utc) - timedelta(hours=24)

    pipeline = [
        {"$match": {"ts": {"$gte": since}}},
        {"$group": {"_id": "$path", "hits": {"$sum": 1}, "last_seen": {"$max": "$ts"}}},
        {"$match": {"hits": {"$gte": 2}}},  # ignore one-off bot pokes
        {"$sort": {"hits": -1}},
        {"$limit": 50},
    ]
    rows = await db[NOT_FOUND_LOG].aggregate(pipeline).to_list(length=50)

    created = 0
    for row in rows:
        path = row["_id"]
        if not path or path in ("/", "") or path.startswith("/api") or path.startswith("/admin"):
            continue
        existing = await db[REDIRECTS].find_one({"_id": path})
        if existing:
            continue

        target = await _suggest_redirect_target(path)
        if not target:
            target = "/tiles"  # safest catch-all

        await db[REDIRECTS].update_one(
            {"_id": path},
            {"$set": {
                "_id": path,
                "target": target,
                "status_code": 301,
                "reason": "auto_404",
                "hits_at_creation": row["hits"],
                "created_at": datetime.now(timezone.utc),
            }},
            upsert=True,
        )
        created += 1
        await _log_action(
            "auto_redirect_created",
            from_path=path, to_path=target, hits=row["hits"],
        )

    return {"ok": True, "redirects_created": created, "candidates_seen": len(rows)}


async def _suggest_redirect_target(path: str) -> str | None:
    """Best-effort match — we have a slug-driven store, so pull the
    last segment of the 404 path, slugify, and look for a tile whose
    name/slug shares ≥2 tokens. Falls back to /tiles if nothing close."""
    db = get_db()
    last = path.rstrip("/").rsplit("/", 1)[-1]
    slug = _slugify(last)
    if not slug:
        return None
    tokens = [t for t in slug.split("-") if len(t) >= 3]
    if not tokens:
        return None
    # Try slug exact-prefix match first
    hit = await db.tiles.find_one(
        {"is_active": True, "slug": {"$regex": f"^{re.escape(slug[:20])}", "$options": "i"}},
        {"_id": 0, "slug": 1},
    )
    if hit and hit.get("slug"):
        return f"/tiles/{hit['slug']}"
    # Fallback — token-overlap on name
    hit = await db.tiles.find_one(
        {"is_active": True, "name": {"$regex": "|".join(re.escape(t) for t in tokens), "$options": "i"}},
        {"_id": 0, "slug": 1},
    )
    if hit and hit.get("slug"):
        return f"/tiles/{hit['slug']}"
    return None


# ────────────────────────────────────────────────────────────────────────
# 4) Algorithm update detector
# ────────────────────────────────────────────────────────────────────────


async def run_algorithm_update_detector() -> dict[str, Any]:
    """Compare yesterday's total clicks to the trailing 7-day mean.
    >25% drop or >50% gain triggers an alert (a Google update or a new
    referrer surge — either way the owner wants to know)."""
    db = get_db()
    admin_doc = await db["gsc_oauth_tokens"].find_one(
        {}, sort=[("last_used_at", -1)], projection={"_id": 1},
    )
    if not admin_doc:
        return {"ok": True, "skipped": True, "reason": "no_gsc"}

    try:
        from services.gsc import _query
        result = await _query(
            admin_doc["_id"], dimensions=["date"], days=8, row_limit=8,
        )
        rows = result.get("rows") or []
    except Exception as exc:
        return {"ok": True, "skipped": True, "reason": f"gsc_error: {exc}"}

    by_date = sorted(
        [{"date": r.get("date") or "", "clicks": int(r.get("clicks") or 0)} for r in rows if r.get("date")],
        key=lambda x: x["date"],
    )
    if len(by_date) < 4:
        return {"ok": True, "skipped": True, "reason": "insufficient_history"}

    yesterday = by_date[-1]
    prior = by_date[:-1]
    avg_prior = sum(d["clicks"] for d in prior) / len(prior) if prior else 0

    if not avg_prior:
        return {"ok": True, "skipped": True, "reason": "no_baseline"}

    delta_pct = ((yesterday["clicks"] - avg_prior) / avg_prior) * 100
    if abs(delta_pct) >= 25:
        direction = "DROP" if delta_pct < 0 else "SURGE"
        try:
            from services.email import send_simple_email_if_possible
            from services.notification_prefs import get_authorized_recipients
            recipients = await get_authorized_recipients("ctr_drop_alerts")
            if recipients:
                color = "#dc2626" if delta_pct < 0 else "#059669"
                html = f"""
                <h2 style='color:{color}'>⚠ SEO traffic {direction} detected</h2>
                <p>Yesterday: <strong>{yesterday['clicks']:,}</strong> clicks
                vs 7-day average: <strong>{avg_prior:,.0f}</strong></p>
                <p>Change: <strong style='color:{color}'>{delta_pct:+.1f}%</strong></p>
                <p>This often signals a Google algorithm update, a referrer change,
                or an indexing problem. Investigate within 48h.</p>
                """
                await send_simple_email_if_possible(
                    to=recipients,
                    subject=f"⚠ SEO traffic {direction.lower()}: {delta_pct:+.0f}% vs baseline",
                    html=html,
                )
            await _log_action(
                "algorithm_alert",
                yesterday_clicks=yesterday["clicks"],
                avg_prior=round(avg_prior),
                delta_pct=round(delta_pct, 1),
                direction=direction,
            )
        except Exception as exc:
            logger.warning("algorithm alert email failed: %s", exc)
        return {"ok": True, "alert": True, "delta_pct": round(delta_pct, 1)}
    return {"ok": True, "alert": False, "delta_pct": round(delta_pct, 1)}


# ────────────────────────────────────────────────────────────────────────
# 5) Brand SERP tracker
# ────────────────────────────────────────────────────────────────────────


BRAND_QUERIES = [
    "tile station",
    "tile station maidstone", "tile station gravesend", "tile station kent",
    "tile station tonbridge", "tile station ashford",
]


async def run_brand_serp_tracker() -> dict[str, Any]:
    """Snapshot positions for brand queries weekly. Alert on any drop
    where we go from page 1 to page 2."""
    db = get_db()
    admin_doc = await db["gsc_oauth_tokens"].find_one(
        {}, sort=[("last_used_at", -1)], projection={"_id": 1},
    )
    if not admin_doc:
        return {"ok": True, "skipped": True, "reason": "no_gsc"}

    try:
        from services.gsc import _query
        result = await _query(
            admin_doc["_id"], dimensions=["query"], days=7, row_limit=500,
        )
        rows = result.get("rows") or []
    except Exception as exc:
        return {"ok": True, "skipped": True, "reason": f"gsc_error: {exc}"}

    snapshot_date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    by_query = {(r.get("query") or "").lower(): r for r in rows}
    drops = []
    for bq in BRAND_QUERIES:
        r = by_query.get(bq)
        position = float((r or {}).get("position") or 0)
        if not position:
            continue
        prev = await db.brand_serp_history.find_one(
            {"query": bq}, sort=[("snapshot_date", -1)],
        )
        await db.brand_serp_history.insert_one({
            "query": bq, "snapshot_date": snapshot_date,
            "position": round(position, 1),
            "clicks": int((r or {}).get("clicks") or 0),
            "impressions": int((r or {}).get("impressions") or 0),
            "ts": datetime.now(timezone.utc),
        })
        if prev and prev.get("position", 0) <= 10 and position > 10:
            drops.append({"query": bq, "before": prev["position"], "after": position})
            await _log_action(
                "brand_serp_drop",
                query=bq, before=prev["position"], after=position,
            )

    if drops:
        try:
            from services.email import send_simple_email_if_possible
            from services.notification_prefs import get_authorized_recipients
            recipients = await get_authorized_recipients("ctr_drop_alerts")
            if recipients:
                rows_html = "".join(
                    f"<tr><td style='padding:8px'>{d['query']}</td>"
                    f"<td style='padding:8px;color:#dc2626'>#{d['before']:.0f} → #{d['after']:.0f}</td></tr>"
                    for d in drops
                )
                html = f"""
                <h2>⚠ Brand SERP drops</h2>
                <p>Brand+location queries fell off page 1 this week:</p>
                <table style='width:100%;border-collapse:collapse'>
                <tr style='background:#f3f4f6'><th align='left' style='padding:8px'>Query</th>
                <th align='left' style='padding:8px'>Position</th></tr>
                {rows_html}</table>
                """
                await send_simple_email_if_possible(
                    to=recipients,
                    subject=f"⚠ Brand SERP: {len(drops)} drops off page 1",
                    html=html,
                )
        except Exception as exc:
            logger.warning("brand SERP alert failed: %s", exc)

    return {"ok": True, "tracked": len(BRAND_QUERIES), "drops": len(drops)}
