"""Seed data for Life Blueprint app: recipes, quotes, podcasts, meditations."""

RECIPES_SEED = [
    {
        "title": "Chicken Seekh Kebab Bowl",
        "cuisine": "Pakistani",
        "meal_type": "Dinner",
        "prep_time": 25,
        "servings": 2,
        "calories": 420,
        "protein": 45,
        "carbs": 8,
        "fat": 22,
        "ingredients": [
            "500g ground chicken breast",
            "1 small onion, finely grated",
            "2 tsp ginger-garlic paste",
            "1 tsp garam masala",
            "1 tsp red chili powder",
            "1 tsp cumin powder",
            "Fresh coriander, chopped",
            "1 green chili, minced",
            "Salt to taste",
            "1 tbsp yogurt",
        ],
        "instructions": [
            "Mix all ingredients in a bowl. Rest for 15 mins.",
            "Shape onto skewers or form kebabs by hand.",
            "Grill on non-stick pan for 4 mins each side until charred.",
            "Serve with cucumber-mint yogurt and a salad of tomato, onion, lemon.",
        ],
        "tags": ["high-protein", "low-carb", "halal"],
        "image": "https://images.unsplash.com/photo-1659275798977-6eee03f687a2",
    },
    {
        "title": "Paneer Bhurji with Eggs",
        "cuisine": "Indian",
        "meal_type": "Breakfast",
        "prep_time": 15,
        "servings": 1,
        "calories": 380,
        "protein": 32,
        "carbs": 6,
        "fat": 25,
        "ingredients": [
            "100g paneer, crumbled",
            "2 eggs, beaten",
            "1/2 onion, diced",
            "1 tomato, diced",
            "1 green chili",
            "1/2 tsp turmeric",
            "1/2 tsp cumin seeds",
            "Fresh coriander",
            "Salt & pepper",
        ],
        "instructions": [
            "Heat ghee or oil. Add cumin seeds.",
            "Sauté onion, chili till soft. Add tomato, turmeric.",
            "Add crumbled paneer, stir 2 mins.",
            "Pour beaten eggs, scramble gently. Garnish coriander.",
        ],
        "tags": ["high-protein", "low-carb", "vegetarian-option"],
        "image": "https://images.unsplash.com/photo-1772795682257-ccb3ac896e4a",
    },
    {
        "title": "Shawarma Chicken Lettuce Wraps",
        "cuisine": "Arab",
        "meal_type": "Lunch",
        "prep_time": 30,
        "servings": 2,
        "calories": 390,
        "protein": 42,
        "carbs": 10,
        "fat": 20,
        "ingredients": [
            "400g chicken thighs, sliced",
            "2 tbsp shawarma spice blend",
            "2 tbsp olive oil",
            "1 lemon, juiced",
            "3 tbsp Greek yogurt (marinade)",
            "Romaine lettuce leaves",
            "Tahini sauce",
            "Cucumber, tomato, red onion",
            "Parsley",
        ],
        "instructions": [
            "Marinate chicken in yogurt, spices, lemon, oil for 30 mins.",
            "Pan-sear on high heat 5-6 mins until golden.",
            "Pile chicken into lettuce leaves with veg and tahini drizzle.",
        ],
        "tags": ["high-protein", "low-carb", "halal"],
        "image": "https://images.unsplash.com/photo-1659275798977-6eee03f687a2",
    },
    {
        "title": "Keema Matar (Low-Carb)",
        "cuisine": "Pakistani",
        "meal_type": "Dinner",
        "prep_time": 35,
        "servings": 3,
        "calories": 450,
        "protein": 38,
        "carbs": 12,
        "fat": 28,
        "ingredients": [
            "500g lean ground beef or lamb",
            "1 cup frozen peas",
            "1 onion, diced",
            "2 tomatoes, chopped",
            "2 tsp ginger-garlic paste",
            "1 tsp garam masala",
            "1 tsp red chili powder",
            "1 tsp coriander powder",
            "Fresh ginger, julienned",
            "Cilantro",
        ],
        "instructions": [
            "Brown onions in ghee. Add ginger-garlic paste.",
            "Add mince, cook till browned. Add tomatoes, spices.",
            "Simmer 15 mins. Add peas, cook 10 mins more.",
            "Garnish with cilantro and ginger.",
        ],
        "tags": ["high-protein", "halal", "comfort"],
        "image": "https://images.unsplash.com/photo-1659275798977-6eee03f687a2",
    },
    {
        "title": "Greek Yogurt Chia Bowl",
        "cuisine": "Mediterranean",
        "meal_type": "Breakfast",
        "prep_time": 5,
        "servings": 1,
        "calories": 310,
        "protein": 24,
        "carbs": 18,
        "fat": 14,
        "ingredients": [
            "200g full-fat Greek yogurt",
            "1 tbsp chia seeds",
            "1 tbsp crushed almonds",
            "1 tbsp crushed walnuts",
            "1/2 tsp cinnamon",
            "1 tsp honey (optional)",
            "A few berries",
        ],
        "instructions": [
            "Combine yogurt, chia, cinnamon.",
            "Top with nuts, berries, drizzle honey.",
        ],
        "tags": ["high-protein", "quick", "vegetarian"],
        "image": "https://images.unsplash.com/photo-1772795682257-ccb3ac896e4a",
    },
    {
        "title": "Egg & Spinach Masala",
        "cuisine": "Indian",
        "meal_type": "Breakfast",
        "prep_time": 15,
        "servings": 1,
        "calories": 340,
        "protein": 26,
        "carbs": 9,
        "fat": 22,
        "ingredients": [
            "3 eggs",
            "2 cups spinach, chopped",
            "1/2 onion",
            "1 tomato",
            "1 green chili",
            "1/2 tsp turmeric",
            "1/2 tsp cumin",
            "Salt to taste",
        ],
        "instructions": [
            "Sauté onion, cumin, chili. Add tomato, turmeric.",
            "Add spinach, wilt 2 mins.",
            "Crack in eggs, scramble with the greens.",
        ],
        "tags": ["high-protein", "low-carb", "vegetarian"],
        "image": "https://images.unsplash.com/photo-1772795682257-ccb3ac896e4a",
    },
    {
        "title": "Grilled Fish Tikka",
        "cuisine": "Pakistani",
        "meal_type": "Dinner",
        "prep_time": 25,
        "servings": 2,
        "calories": 360,
        "protein": 48,
        "carbs": 4,
        "fat": 16,
        "ingredients": [
            "500g firm white fish (cod or tilapia)",
            "3 tbsp Greek yogurt",
            "1 tsp tikka masala",
            "1 tsp ginger-garlic paste",
            "1 tsp lemon juice",
            "1 tsp paprika",
            "Salt",
        ],
        "instructions": [
            "Marinate fish in yogurt, spices, lemon for 20 mins.",
            "Grill or pan-sear 4 mins each side.",
            "Serve with cucumber raita and mint chutney.",
        ],
        "tags": ["high-protein", "low-carb", "halal"],
        "image": "https://images.unsplash.com/photo-1659275798977-6eee03f687a2",
    },
    {
        "title": "Labneh & Za'atar Plate",
        "cuisine": "Arab",
        "meal_type": "Snack",
        "prep_time": 5,
        "servings": 1,
        "calories": 280,
        "protein": 14,
        "carbs": 7,
        "fat": 22,
        "ingredients": [
            "150g labneh",
            "1 tbsp za'atar",
            "2 tbsp olive oil",
            "Cucumber sticks",
            "Cherry tomatoes",
            "Mint leaves",
        ],
        "instructions": [
            "Spread labneh on plate.",
            "Drizzle oil, sprinkle za'atar.",
            "Serve with vegetables.",
        ],
        "tags": ["quick", "vegetarian", "low-carb"],
        "image": "https://images.unsplash.com/photo-1772795682257-ccb3ac896e4a",
    },
    {
        "title": "Roasted Chickpea Crunch",
        "cuisine": "Mediterranean",
        "meal_type": "Snack",
        "prep_time": 30,
        "servings": 4,
        "calories": 180,
        "protein": 9,
        "carbs": 22,
        "fat": 6,
        "ingredients": [
            "2 cans chickpeas, drained and dried",
            "2 tbsp olive oil",
            "1 tsp paprika",
            "1 tsp cumin",
            "1/2 tsp cayenne",
            "Salt",
        ],
        "instructions": [
            "Preheat oven to 200°C.",
            "Toss chickpeas with oil and spices.",
            "Roast 25-30 mins until crispy.",
        ],
        "tags": ["vegetarian", "crunchy"],
        "image": "https://images.unsplash.com/photo-1772795682257-ccb3ac896e4a",
    },
    {
        "title": "Chicken Karahi (Dry)",
        "cuisine": "Pakistani",
        "meal_type": "Dinner",
        "prep_time": 40,
        "servings": 3,
        "calories": 480,
        "protein": 46,
        "carbs": 10,
        "fat": 28,
        "ingredients": [
            "700g chicken, bone-in",
            "4 tomatoes, chopped",
            "2 tbsp ginger-garlic paste",
            "2 green chilies",
            "1 tsp red chili flakes",
            "1 tsp cumin",
            "1 tsp coriander",
            "Fresh ginger, julienned",
            "Cilantro",
        ],
        "instructions": [
            "Heat oil, add chicken, brown 5 mins.",
            "Add ginger-garlic paste, cook 2 mins.",
            "Add tomatoes and spices, cover, cook 25 mins.",
            "Uncover, reduce liquid. Garnish ginger, cilantro, chilies.",
        ],
        "tags": ["high-protein", "halal", "special"],
        "image": "https://images.unsplash.com/photo-1659275798977-6eee03f687a2",
    },
    {
        "title": "Tandoori Cauliflower Steak",
        "cuisine": "Indian",
        "meal_type": "Lunch",
        "prep_time": 30,
        "servings": 2,
        "calories": 220,
        "protein": 12,
        "carbs": 18,
        "fat": 12,
        "ingredients": [
            "1 large cauliflower, cut in thick slabs",
            "3 tbsp Greek yogurt",
            "1 tbsp tandoori masala",
            "1 tsp ginger-garlic paste",
            "1 tsp lemon juice",
            "Salt",
        ],
        "instructions": [
            "Mix marinade, brush generously over cauliflower slabs.",
            "Roast at 220°C for 25 mins, flipping halfway.",
            "Serve with mint yogurt.",
        ],
        "tags": ["vegetarian", "low-carb"],
        "image": "https://images.unsplash.com/photo-1772795682257-ccb3ac896e4a",
    },
    {
        "title": "Lamb Kofta Skewers",
        "cuisine": "Arab",
        "meal_type": "Dinner",
        "prep_time": 30,
        "servings": 3,
        "calories": 440,
        "protein": 40,
        "carbs": 6,
        "fat": 28,
        "ingredients": [
            "600g ground lamb",
            "1 onion, grated",
            "2 tbsp parsley",
            "1 tsp cumin",
            "1 tsp allspice",
            "1 tsp sumac",
            "Salt",
        ],
        "instructions": [
            "Combine all ingredients, chill 30 mins.",
            "Shape onto skewers.",
            "Grill 4 mins each side.",
            "Serve with tahini and tabbouleh.",
        ],
        "tags": ["high-protein", "halal", "grill"],
        "image": "https://images.unsplash.com/photo-1659275798977-6eee03f687a2",
    },
]

QUOTES_SEED = [
    {"text": "The wound is the place where the Light enters you.", "author": "Rumi", "category": "Wisdom"},
    {"text": "What you seek is seeking you.", "author": "Rumi", "category": "Wisdom"},
    {"text": "He who has a why to live for can bear almost any how.", "author": "Viktor Frankl", "category": "Purpose"},
    {"text": "You have power over your mind — not outside events. Realize this, and you will find strength.", "author": "Marcus Aurelius", "category": "Stoic"},
    {"text": "We suffer more often in imagination than in reality.", "author": "Seneca", "category": "Stoic"},
    {"text": "The soul becomes dyed with the color of its thoughts.", "author": "Marcus Aurelius", "category": "Stoic"},
    {"text": "Discipline equals freedom.", "author": "Jocko Willink", "category": "Discipline"},
    {"text": "Do not go gentle into that good night. Rage, rage against the dying of the light.", "author": "Dylan Thomas", "category": "Resilience"},
    {"text": "The best revenge is massive success.", "author": "Frank Sinatra", "category": "Motivation"},
    {"text": "Fall seven times, stand up eight.", "author": "Japanese Proverb", "category": "Resilience"},
    {"text": "Sabr (patience) is beautiful.", "author": "Qur'an 12:18", "category": "Spiritual"},
    {"text": "Indeed, with hardship comes ease.", "author": "Qur'an 94:6", "category": "Spiritual"},
    {"text": "A year from now you'll wish you had started today.", "author": "Karen Lamb", "category": "Action"},
    {"text": "The cave you fear to enter holds the treasure you seek.", "author": "Joseph Campbell", "category": "Courage"},
    {"text": "Out beyond ideas of wrongdoing and rightdoing, there is a field. I'll meet you there.", "author": "Rumi", "category": "Peace"},
    {"text": "Silence is not empty. It is full of answers.", "author": "Unknown", "category": "Peace"},
    {"text": "How we spend our days is, of course, how we spend our lives.", "author": "Annie Dillard", "category": "Purpose"},
    {"text": "You are not a drop in the ocean. You are the entire ocean in a drop.", "author": "Rumi", "category": "Wisdom"},
    {"text": "Begin at once to live, and count each separate day as a separate life.", "author": "Seneca", "category": "Stoic"},
    {"text": "The obstacle is the way.", "author": "Marcus Aurelius", "category": "Stoic"},
    {"text": "Comparison is the thief of joy.", "author": "Theodore Roosevelt", "category": "Wisdom"},
    {"text": "Man only likes to count his troubles; he doesn't calculate his happiness.", "author": "Dostoevsky", "category": "Wisdom"},
    {"text": "To be beautiful means to be yourself. You don't need to be accepted by others. You need to accept yourself.", "author": "Thich Nhat Hanh", "category": "Peace"},
    {"text": "The best way out is always through.", "author": "Robert Frost", "category": "Resilience"},
    {"text": "You must be willing to let go of the life you planned, so as to have the life that is waiting for you.", "author": "Joseph Campbell", "category": "Courage"},
    {"text": "Whoever is happy will make others happy too.", "author": "Anne Frank", "category": "Peace"},
    {"text": "When you realize nothing is lacking, the whole world belongs to you.", "author": "Lao Tzu", "category": "Peace"},
    {"text": "Don't explain your philosophy. Embody it.", "author": "Epictetus", "category": "Stoic"},
    {"text": "The journey of a thousand miles begins with a single step.", "author": "Lao Tzu", "category": "Action"},
    {"text": "Nothing is softer or more flexible than water, yet nothing can resist it.", "author": "Lao Tzu", "category": "Wisdom"},
    {"text": "When you have a purpose, your footing is sure.", "author": "Mary Oliver", "category": "Purpose"},
    {"text": "Gratitude turns what we have into enough.", "author": "Aesop", "category": "Gratitude"},
    {"text": "The present moment is the only moment available to us, and it is the door to all moments.", "author": "Thich Nhat Hanh", "category": "Peace"},
    {"text": "Between stimulus and response, there is a space. In that space is our power.", "author": "Viktor Frankl", "category": "Wisdom"},
    {"text": "Watch your thoughts, they become words; words, they become actions; actions, they become habits; habits, they become character; character becomes your destiny.", "author": "Lao Tzu", "category": "Discipline"},
    {"text": "Do what you can, with what you have, where you are.", "author": "Theodore Roosevelt", "category": "Action"},
    {"text": "The mind that opens to a new idea never returns to its original size.", "author": "Albert Einstein", "category": "Wisdom"},
    {"text": "Courage is resistance to fear, mastery of fear — not absence of fear.", "author": "Mark Twain", "category": "Courage"},
    {"text": "Happiness depends upon ourselves.", "author": "Aristotle", "category": "Wisdom"},
    {"text": "Every moment is a fresh beginning.", "author": "T.S. Eliot", "category": "Action"},
]

PODCASTS_SEED = [
    {"title": "Jordan Peterson — Purpose & Meaning", "youtube_id": "nXc-zvHa-GA", "host": "Jordan Peterson", "category": "Wisdom", "duration": "8 min"},
    {"title": "Goggins — Stay Hard", "youtube_id": "jlA2dWVLFzg", "host": "David Goggins", "category": "Discipline", "duration": "30 min"},
    {"title": "Alan Watts — What Do You Desire?", "youtube_id": "GqGksNRYu8s", "host": "Alan Watts", "category": "Philosophy", "duration": "3 min"},
    {"title": "Alan Watts — What If Money Was No Object", "youtube_id": "ERbvKrH-GC4", "host": "Alan Watts", "category": "Philosophy", "duration": "3 min"},
    {"title": "Les Brown — It's Possible", "youtube_id": "lsSC2vx7zFQ", "host": "Les Brown", "category": "Motivation", "duration": "10 min"},
    {"title": "Naval Ravikant — How to Get Rich (Without Getting Lucky)", "youtube_id": "1-TZqOsVCNM", "host": "Naval", "category": "Wisdom", "duration": "30 min"},
    {"title": "Matthew McConaughey — This Is Your Time", "youtube_id": "wD2cVhC-63I", "host": "Matthew McConaughey", "category": "Motivation", "duration": "6 min"},
    {"title": "Eckhart Tolle — The Power of Now", "youtube_id": "5IEsBKZu3RQ", "host": "Eckhart Tolle", "category": "Peace", "duration": "10 min"},
    {"title": "Rumi — The Guest House (Guided)", "youtube_id": "RXBOtMkAalw", "host": "Various", "category": "Spiritual", "duration": "7 min"},
    {"title": "Simon Sinek — Start With Why (TED)", "youtube_id": "u4ZoJKF_VuA", "host": "Simon Sinek", "category": "Wisdom", "duration": "18 min"},
    {"title": "Steve Jobs — Stanford Commencement", "youtube_id": "UF8uR6Z6KLc", "host": "Steve Jobs", "category": "Wisdom", "duration": "15 min"},
    {"title": "Tim Ferriss — Fear Setting (TED)", "youtube_id": "5J6jAC6XxAI", "host": "Tim Ferriss", "category": "Philosophy", "duration": "13 min"},
    {"title": "Brené Brown — The Power of Vulnerability", "youtube_id": "iCvmsMzlF7o", "host": "Brené Brown", "category": "Wisdom", "duration": "20 min"},
    {"title": "Denzel Washington — Fall Forward", "youtube_id": "tbnzAVRZ9Xc", "host": "Denzel Washington", "category": "Motivation", "duration": "13 min"},
    {"title": "Joe Rogan × Jordan Peterson — On Meaning", "youtube_id": "sY8aFSY2zv4", "host": "Joe Rogan", "category": "Wisdom", "duration": "20 min"},
    {"title": "Mo Gawdat — 3 Questions That End Unhappiness", "youtube_id": "yX18EpR4qSg", "host": "Mo Gawdat", "category": "Peace", "duration": "16 min"},
    {"title": "Mo Gawdat × Simon Sinek — Your Unhappy Brain", "youtube_id": "47wZCt0YG_A", "host": "Mo Gawdat", "category": "Peace", "duration": "90 min"},
]

MEDITATIONS_SEED = [
    {"title": "10-Minute Morning Calm", "youtube_id": "inpok4MKVLM", "category": "Morning", "duration": "10 min", "description": "Start your day grounded and present."},
    {"title": "Body Scan for Deep Rest", "youtube_id": "ihwcw_ofuME", "category": "Sleep", "duration": "20 min", "description": "Release tension from head to toe."},
    {"title": "Anxiety Relief Breath", "youtube_id": "MR57rug8NsM", "category": "Calm", "duration": "5 min", "description": "Box breathing for instant calm."},
    {"title": "Gratitude Meditation", "youtube_id": "OCorElLKFQE", "category": "Gratitude", "duration": "10 min", "description": "Cultivate thankfulness."},
    {"title": "Guided Walking Meditation", "youtube_id": "8PFKIu3pl0k", "category": "Movement", "duration": "15 min", "description": "Mindfulness on the move."},
    {"title": "Loving-Kindness (Metta)", "youtube_id": "sz7cpV7ERsM", "category": "Heart", "duration": "12 min", "description": "Open your heart to self and others."},
    {"title": "Sadhguru — Isha Kriya", "youtube_id": "EwQkfoKxRvo", "category": "Morning", "duration": "15 min", "description": "Breath-based practice for mind-body balance."},
    {"title": "Sadhguru — 5-Minute Morning Reset", "youtube_id": "N2LdjfAgkUM", "category": "Morning", "duration": "5 min", "description": "A quick start for an effortless day."},
    {"title": "Tara Brach — Letting Go", "youtube_id": "-40Tgg07J9A", "category": "Calm", "duration": "16 min", "description": "Release tension and thoughts into awareness."},
    {"title": "Tara Brach — Inner Refuge of Calm", "youtube_id": "dmprAiDCtVw", "category": "Calm", "duration": "20 min", "description": "Breath, body scan, and quiet presence."},
    {"title": "Lavendaire — Stress & Anxiety Release", "youtube_id": "H_uc-uQ3Nkc", "category": "Calm", "duration": "10 min", "description": "Body scan with gentle affirmations."},
    {"title": "Headspace — The Basics", "youtube_id": "ssss7V1_eyA", "category": "Morning", "duration": "10 min", "description": "Simple grounding meditation for beginners."},
    {"title": "Pema Chödrön — Tonglen", "youtube_id": "QwqlurCvXuM", "category": "Heart", "duration": "15 min", "description": "Give and receive for compassionate awareness."},
    {"title": "Great Meditation — Just Breathe", "youtube_id": "y6iTjoN407U", "category": "Calm", "duration": "10 min", "description": "A simple breath-focused reset."},
    {"title": "Great Meditation — Mindful Morning", "youtube_id": "M3fjH45BUz4", "category": "Morning", "duration": "10 min", "description": "Quiet mental noise, center your breath."},
]

AFFIRMATIONS_SEED = [
    "I am building a life I am proud of, one honest day at a time.",
    "My body is strong, my mind is calm, my heart is open.",
    "I deserve rest, joy, and nourishment.",
    "I am the architect of my next 40 years.",
    "Every step I take today is an investment in the man I am becoming.",
    "I meet challenges with patience and courage.",
    "I am not behind. I am exactly where I need to begin.",
    "My discipline is a form of self-love.",
]
