/**
 * SEO Autopilot — admin audit + manual triggers.
 * Read-only summary by default; super-admins also get "Run now" buttons
 * for each of the 8 autonomous jobs.
 */
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  ArrowLeft, RefreshCw, Loader2, Bot, Activity, Link2, FileWarning,
  Zap, Crown, Image as ImageIcon, Gauge, AlertTriangle,
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '../../components/ui/card';
import { Button } from '../../components/ui/button';
import { Badge } from '../../components/ui/badge';
import { toast } from 'sonner';
import { useAuth } from '../../contexts/AuthContext';

const API = `${process.env.REACT_APP_BACKEND_URL || ''}/api`;

const JOBS = [
  { id: 'cannibalization',     label: 'Keyword cannibalization',  cadence: 'Daily 07:00',          icon: Link2,        what: 'When 2 of your URLs target the same query, auto-canonicalises the loser to the winner.' },
  { id: '404',                 label: '404 → 301 redirect',       cadence: 'Daily 07:15',          icon: FileWarning,  what: 'Any URL hit by ≥2 visitors and returning 404 in the last 24h gets an auto-301.' },
  { id: 'stale',               label: 'Stale page refresher',     cadence: 'Sun 07:30',            icon: RefreshCw,    what: 'City pages older than 180 days get auto-regenerated by the existing AI.' },
  { id: 'brand_serp',          label: 'Brand SERP tracker',       cadence: 'Mon 07:45',            icon: Crown,        what: 'Snapshots brand+location query positions weekly and alerts on page-1 drops.' },
  { id: 'algo',                label: 'Algorithm update detector',cadence: 'Daily 08:00',          icon: AlertTriangle,what: 'Sudden traffic shift >25% vs 7-day baseline triggers an email alert.' },
  { id: 'alt_text',            label: 'Image alt-text backfill',  cadence: 'Daily 04:00',          icon: ImageIcon,    what: 'Generates SEO alt text via Gemini for every product image without one.' },
  { id: 'web_vitals_aggregate',label: 'Web Vitals aggregator',    cadence: 'Every 6 hrs',          icon: Gauge,        what: 'Computes p75 LCP/INP/CLS per page from the browser beacon.' },
  { id: 'web_vitals_alert',    label: 'Web Vitals alerts',        cadence: 'Daily 09:15',          icon: Zap,          what: 'Emails when any page slows >20% LCP, >50% INP or +0.05 CLS vs prior week.' },
  { id: 'weekly_summary',      label: 'Weekly summary email',     cadence: 'Mon 08:30',            icon: Activity,     what: 'Peace-of-mind email — counts every auto-fix the autopilot did over the last 7 days. Goes to anyone subscribed to "Daily SEO digest".' },
];

const ACTION_LABELS = {
  cannibalization_canonical: { label: 'Canonical override', color: 'bg-purple-100 text-purple-700' },
  stale_page_refresh:        { label: 'Stale page refreshed', color: 'bg-blue-100 text-blue-700' },
  stale_page_marked:         { label: 'Stale page flagged', color: 'bg-amber-100 text-amber-700' },
  auto_redirect_created:     { label: 'Auto 301 created', color: 'bg-emerald-100 text-emerald-700' },
  algorithm_alert:           { label: 'Algorithm alert', color: 'bg-red-100 text-red-700' },
  brand_serp_drop:           { label: 'Brand SERP drop', color: 'bg-red-100 text-red-700' },
};

export default function SeoAutopilot() {
  const { token } = useAuth();
  const navigate = useNavigate();
  const headers = useMemo(() => (token ? { Authorization: `Bearer ${token}` } : {}), [token]);
  const [summary, setSummary] = useState(null);
  const [actions, setActions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [running, setRunning] = useState(null);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const [s, a] = await Promise.all([
        fetch(`${API}/admin/seo-autopilot/summary`, { headers }).then(r => r.json()),
        fetch(`${API}/admin/seo-autopilot/actions?limit=100`, { headers }).then(r => r.json()),
      ]);
      setSummary(s);
      setActions(a.actions || []);
    } catch (e) {
      toast.error(e.message);
    } finally {
      setLoading(false);
    }
  }, [headers]);

  useEffect(() => { load(); }, [load]);

  const runJob = async (jobId) => {
    setRunning(jobId);
    try {
      const res = await fetch(`${API}/admin/seo-autopilot/run/${jobId}`, {
        method: 'POST', headers,
      });
      const json = await res.json();
      if (!res.ok) throw new Error(json.detail || 'Run failed');
      toast.success(`${jobId}: ${json.skipped ? `skipped (${json.reason})` : 'done'}`);
      await load();
    } catch (e) {
      toast.error(`${jobId} → ${e.message}`);
    } finally {
      setRunning(null);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50">
      <div className="bg-white border-b border-slate-200 px-6 py-4 sticky top-0 z-10">
        <div className="flex items-center justify-between max-w-7xl mx-auto">
          <div className="flex items-center gap-4">
            <button onClick={() => navigate('/admin/seo')} className="p-2 hover:bg-slate-100 rounded-lg" data-testid="autopilot-back-btn">
              <ArrowLeft className="w-5 h-5" />
            </button>
            <div className="flex items-center gap-3">
              <div className="bg-emerald-100 p-2 rounded-lg">
                <Bot className="w-6 h-6 text-emerald-600" />
              </div>
              <div>
                <h1 className="text-xl font-bold text-slate-900">SEO Autopilot</h1>
                <p className="text-sm text-slate-500">8 autonomous jobs · zero human review · audit trail below.</p>
              </div>
            </div>
          </div>
          <Button variant="outline" onClick={load} disabled={loading} data-testid="autopilot-refresh-btn">
            <RefreshCw className={`w-4 h-4 mr-2 ${loading ? 'animate-spin' : ''}`} />
            Refresh
          </Button>
        </div>
      </div>

      <div className="max-w-7xl mx-auto p-6 space-y-6">
        {/* Summary metrics */}
        {summary && (
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-4">
            {[
              { k: 'actions_total',          label: 'Total auto-fixes',     icon: Activity },
              { k: 'canonical_overrides',    label: 'Canonical fixes',      icon: Link2 },
              { k: 'redirects',              label: '301 redirects',        icon: FileWarning },
              { k: 'brand_serp_snapshots',   label: 'Brand SERP snaps',     icon: Crown },
              { k: 'stale_pages_marked',     label: 'Pages flagged stale',  icon: RefreshCw },
              { k: 'actions_last_30d',       label: 'Actions (30d)',        icon: Zap },
            ].map(({ k, label, icon: Icon }) => (
              <Card key={k}>
                <CardContent className="p-4">
                  <div className="flex items-center gap-2">
                    <Icon className="w-4 h-4 text-emerald-600" />
                    <span className="text-xs text-slate-500 uppercase tracking-wide">{label}</span>
                  </div>
                  <p className="text-2xl font-bold mt-1">{(summary[k] ?? 0).toLocaleString()}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        )}

        {/* Job grid */}
        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Jobs</CardTitle>
            <CardDescription>All run on schedule — no action needed. Force-run for debugging only.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {JOBS.map((j) => (
                <div key={j.id} className="border border-slate-200 rounded-xl p-4 flex items-start gap-3" data-testid={`autopilot-job-${j.id}`}>
                  <div className="bg-slate-100 p-2 rounded-lg flex-shrink-0">
                    <j.icon className="w-5 h-5 text-slate-700" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between gap-2">
                      <p className="font-semibold text-sm text-slate-900">{j.label}</p>
                      <Badge variant="outline" className="text-[10px]">{j.cadence}</Badge>
                    </div>
                    <p className="text-xs text-slate-500 mt-1">{j.what}</p>
                    <Button
                      variant="outline" size="sm"
                      onClick={() => runJob(j.id)}
                      disabled={running === j.id}
                      className="mt-2 h-7 text-xs"
                      data-testid={`autopilot-run-${j.id}`}
                    >
                      {running === j.id ? <Loader2 className="w-3 h-3 animate-spin mr-1" /> : null}
                      Run now
                    </Button>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Audit log */}
        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Audit log</CardTitle>
            <CardDescription>Most recent {actions.length} autonomous actions.</CardDescription>
          </CardHeader>
          <CardContent>
            {actions.length === 0 ? (
              <p className="text-sm text-slate-400 italic text-center py-8">No actions yet — they'll start appearing as the cron jobs fire.</p>
            ) : (
              <ul className="divide-y divide-slate-100">
                {actions.map((a, i) => {
                  const meta = ACTION_LABELS[a.action_type] || { label: a.action_type, color: 'bg-slate-100 text-slate-700' };
                  return (
                    <li key={i} className="py-2 flex items-center gap-3 text-sm" data-testid={`autopilot-action-${i}`}>
                      <Badge className={`${meta.color} border-0`}>{meta.label}</Badge>
                      <span className="text-xs text-slate-400 font-mono">{a.ts ? new Date(a.ts).toLocaleString('en-GB') : '—'}</span>
                      <span className="text-slate-600 text-xs truncate flex-1">
                        {a.query ? `“${a.query}” · ` : ''}
                        {a.from_path ? `${a.from_path} → ${a.to_path}` : ''}
                        {a.loser_path ? `${a.loser_path} ⇒ ${a.winner_url}` : ''}
                        {a.slug ? `slug: ${a.slug}` : ''}
                        {a.delta_pct ? `${a.delta_pct >= 0 ? '+' : ''}${a.delta_pct}% (${a.direction})` : ''}
                      </span>
                    </li>
                  );
                })}
              </ul>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
